name: DEV PR Build

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    # MAUI Workload restore
    - name: MAUI Workload restore
      run: dotnet workload restore --project "PassStorage3\PassStorage3.App\PassStorage3.App.csproj"
      
    # Build solution
    - name: Build solution
      run: dotnet build PassStorage3\PassStorage3.sln

    # Execute all unit tests in the solution
    - name: Execute unit tests (PassStorage3.Crypto)
      run: dotnet test PassStorage3\PassStorage3.Crypto.Tests\PassStorage3.Crypto.Tests.csproj
      
    # Execute all unit tests in the solution
    - name: Execute unit tests (PassStorage3.Data)
      run: dotnet test PassStorage3\PassStorage3.Data.Tests\PassStorage3.Data.Tests.csproj

    # Publish
    - name: Publish application
      run: dotnet publish PassStorage3\PassStorage3.App\PassStorage3.App.csproj -f net7.0-windows10.0.19041.0 -p:WindowsPackageType=None -p:SelfContained=true -p:WindowsAppSDKSelfContained=true
